name: "🌀 RR Version Check"

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      # check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # download the latest version file and overwrite target
      - name: Update Version File
        run: |
          URL="http://update.rwfc.net:8000/RetroRewind/RetroRewindVersion.txt"
          TARGET="versions.txt"
          
          # Download with a specific user agent
          curl -s -L -A "GitHub-Action-RR-Updater" -o "$TARGET" "$URL"
          
      # check for changes and commit only if git detects a difference
      - name: Check and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add versions.txt
          
          # Check if there is anything to commit
          if ! git diff --staged --quiet; then
            echo "Changes detected, committing..."
            git commit -m "🏎️ RR versions .txt updated"
            git push
          else
            echo "No content changes detected (ignoring line endings)."
          fi